version: '3.8'

services:

  todo-list:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    environment:
      DATABASE_URL: "host=postgres user=postgres password=yourpassword dbname=taskdb port=5432 sslmode=disable TimeZone=UTC"
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres_data: