version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "host=postgres user=postgres password=yourpassword dbname=taskdb port=5432 sslmode=disable TimeZone=UTC"
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres_data: