version: '3.8'

services:

  todo-list:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    environment:
        POSTGRES_HOST: shared-db
        POSTGRES_PORT: 5432
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: yourpassword
        POSTGRES_DB: shared_db
        POSTGRES_SSLMODE: disable
        POSTGRES_TIMEZONE: UTC
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres_data:

