version: '3.8'

services:

  todo-list:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-todo-list
    environment:
        POSTGRES_HOST: shared-db
        POSTGRES_PORT: 5432
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: yourpassword
        POSTGRES_DB: shared_db
        POSTGRES_SSLMODE: disable
        POSTGRES_TIMEZONE: UTC
        ALLOWED_ORIGINS: http://localhost:8080
        KEYCLOAK_PUBLIC_KEY: MIICmzCCAYMCBgGWFpkvJDANBgkqhkiG9w0BAQsFADARMQ8wDQYDVQQDDAZtYXN0ZXIwHhcNMjUwNDA4MTgwOTIwWhcNMzUwNDA4MTgxMTAwWjARMQ8wDQYDVQQDDAZtYXN0ZXIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDJznCSQCjovIPnneSfHKv2QgQCkp0PnoOoMndRIT1p6GNNlU2sysvmTUMas5UYsdVeHKHBeuTqL9AhcNIhENw2WgHFtvSw377Qd8uwX/MczrBdD2Lxl1zNAprzaQUHm4xBDa8UrKZmoffVVfELAmVYq5UA1Jp8nqiQuFcGdiAzb/CSCU3HfW0THKNuCBG1TLoyyNVpdX3P86kEQQFE7Gx0JkAm7woAkdpBhR2YteDc+dfDLWxSCk/zqUnhWtxccqHRdhzsz9PnQegX3cAikVGhWz5GnRgnnEumugdORiWLB+qSqTiFabp654E7Qe77YsAqXGSJhOr0nP5UAxc2IbvFAgMBAAEwDQYJKoZIhvcNAQELBQADggEBALWbfUWyQ6MSMbSRMJoD3ELPXjk27rcHbddLQRtNtdQ+/hxvGpOck+6+GmkzkcA1kpTfCggJJ3MVFBHYCMvcGZAiqinfhQTqN0f45A4ul5cY4mv+sSgkZ9XSbs7vTp+YvNa2pIF7jFBLXTX/5SOevnsNRFd3sRlLyqsExJ85CqVKJuGT4l9yXlhVn9C858UA+ACuvgTtQpQSnVdZozj5Cl4gxP289i7w+ilBY/L16IXcneQNSGwMFmSZahNhRsicUT+efvOKFk120CYjjCGPeoPd5tI4guKSGwuRVTDtXQzs/gof+nFmUKjHDnsykMd/oen1TI3J2NoaGrkDvaBbPxU=
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  app-network:
    external: true

